package nervouschef;

import java.awt.event.ActionListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author lailx
 */
public class GameOverPanel extends javax.swing.JPanel {

    /**
     * Creates new form GameOverPanel
     */
    public GameOverPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scoreLabel = new javax.swing.JLabel();
        restartButton = new javax.swing.JButton();
        resumeButton = new javax.swing.JButton();
        gameOverLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        scoreLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(0, 0, 153));
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel.setText("Score: ");
        scoreLabel.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 146;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 43, 0, 0);
        add(scoreLabel, gridBagConstraints);

        restartButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        restartButton.setForeground(new java.awt.Color(51, 0, 153));
        restartButton.setText("Restart");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 23, 14, 0);
        add(restartButton, gridBagConstraints);

        resumeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resumeButton.setForeground(new java.awt.Color(51, 0, 153));
        resumeButton.setText("Resume");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 38, 14, 0);
        add(resumeButton, gridBagConstraints);

        gameOverLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        gameOverLabel.setForeground(new java.awt.Color(51, 0, 153));
        gameOverLabel.setText("Game Over ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(54, 57, 0, 0);
        add(gameOverLabel, gridBagConstraints);

        exitButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(51, 0, 153));
        exitButton.setText("Exit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 38, 14, 23);
        add(exitButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

// registers listener when restart button is clicked and MainFrame should call it
    public void setRestartListener(ActionListener listener) {
        restartButton.addActionListener(listener);
    }

    // registers listener when resume button is clicked and MainFrame should call it
    public void setResumeListener(ActionListener listener) {
        resumeButton.addActionListener(listener);
    }
    
    // registers listener when exit button is clicked and MainFrame should call it
    public void setExitListener(ActionListener listener) {
        exitButton.addActionListener(listener);
    }

    public void setScore(int score) {
        scoreLabel.setText("Score: " + score);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel gameOverLabel;
    private javax.swing.JButton restartButton;
    private javax.swing.JButton resumeButton;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables

}
