/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nervouschef;

import java.awt.event.ActionListener;

/**
 *
 * @author lailx
 */
public class GameScreen extends javax.swing.JPanel {

    private final GamePanel gamePanel;

    /**
     * Creates new form GameScreen
     */
    public GameScreen() {
        initComponents();
        gamePanel = new GamePanel();
        add(gamePanel, java.awt.BorderLayout.CENTER);

    }

    // starts game loop allows rendering to begin
    public void startGameLoop() {
        gamePanel.startGameLoop();
    }

    // stops game loop pausing all game updates and rendering
    public void stopGameLoop() {
        gamePanel.stopGameLoop();
    }
    
    // resets game to initial state
    public void reset() {
        gamePanel.reset();
    }
    
    // updates score on screen
    public void setScore(int score) {
        scoreLabel.setText("Score: " + score);
        
    }
    
    //updates timer  displayed on screen
    public void setTimer(String time) {
        timerLabel.setText("Time: " + time);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hudPanel = new javax.swing.JPanel();
        scoreLabel = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();
        pauseGameButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        scoreLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(51, 0, 153));
        scoreLabel.setText("Score: ");

        timerLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timerLabel.setForeground(new java.awt.Color(51, 0, 153));
        timerLabel.setText("Time: ");

        javax.swing.GroupLayout hudPanelLayout = new javax.swing.GroupLayout(hudPanel);
        hudPanel.setLayout(hudPanelLayout);
        hudPanelLayout.setHorizontalGroup(
            hudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hudPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scoreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(timerLabel)
                .addGap(17, 17, 17))
        );
        hudPanelLayout.setVerticalGroup(
            hudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hudPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(hudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timerLabel)
                    .addComponent(scoreLabel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(hudPanel, java.awt.BorderLayout.PAGE_START);

        pauseGameButton.setText("Pause Game");
        add(pauseGameButton, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    // registers listener when pause button is clicked and MainFrame should call it
    public void setPauseListener(ActionListener listener) {
        pauseGameButton.addActionListener(listener);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel hudPanel;
    private javax.swing.JButton pauseGameButton;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel timerLabel;
    // End of variables declaration//GEN-END:variables
}
