package nervouschef;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author lailx
 */
public class MainFrame extends javax.swing.JFrame {

    private MenuPanel menuPanel;
    private GameOverPanel gameOverPanel;
    private GameScreen gameScreen;

    private java.awt.CardLayout cardLayout;

    private static final String MENU = "MENU";
    private static final String GAME_OVER = "GAME_OVER";
    private static final String GAME = "GAME";

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        menuPanel = new MenuPanel();
        gameOverPanel = new GameOverPanel();
        gameScreen = new GameScreen();
        cardLayout = (java.awt.CardLayout) cardPanel.getLayout();

        cardPanel.add(menuPanel, MENU);
        cardPanel.add(gameOverPanel, GAME_OVER);
        cardPanel.add(gameScreen, GAME);

        menuPanel.setStartListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showGame();
            }
        });

        gameOverPanel.setExitListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showMenu();
            }
        });

        gameOverPanel.setRestartListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showGame();
            }
        });

        gameScreen.setEndListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showGameOver();
            }
        });

        showMenu();
        pack();
        setLocationRelativeTo(null);

    }

    public void showMenu() {
        cardLayout.show(cardPanel, MENU);

    }

    public void showGameOver() {
        cardLayout.show(cardPanel, GAME_OVER);
    }

    public void showGame() {
        cardLayout.show(cardPanel, GAME);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        cardPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(cardPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    // End of variables declaration//GEN-END:variables

}
