/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nervouschef;

import java.awt.event.ActionListener;

/**
 *
 * @author lailx
 */
public class PausePanel extends javax.swing.JPanel {

    /**
     * Creates new form PausePanel
     */
    public PausePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        resumeButton = new javax.swing.JButton();
        restartButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        resumeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resumeButton.setForeground(new java.awt.Color(51, 0, 153));
        resumeButton.setText("Resume");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(130, 97, 147, 0);
        add(resumeButton, gridBagConstraints);

        restartButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        restartButton.setForeground(new java.awt.Color(51, 0, 153));
        restartButton.setText("Restart");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(130, 50, 147, 103);
        add(restartButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // registers listener when resume button is clicked and MainFrame should call it
    public void setResumeListener(ActionListener listener) {
        resumeButton.addActionListener(listener);
    }

    // registers listener when restart button is clicked and MainFrame should call it
    public void setRestartListener(ActionListener listener) {
        restartButton.addActionListener(listener);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton restartButton;
    private javax.swing.JButton resumeButton;
    // End of variables declaration//GEN-END:variables
}
